package aipipeline

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"math/rand"
	"net/http"
	"strings"
	"time"
)

const (
	geminiBase  = "https://generativelanguage.googleapis.com/v1beta"
	flashModel  = "gemini-2.5-flash"
	imagenModel = "imagen-4.0-fast-generate-001"
)

// PromptAnalysis holds the structured result of Gemini's prompt analysis.
type PromptAnalysis struct {
	CharacterType string   `json:"character_type"`
	Subclass      string   `json:"subclass"`
	Category      string   `json:"category"`
	Tags          []string `json:"tags"`
	Rarity        string   `json:"rarity"`
	ImagePrompt   string   `json:"image_prompt"`
}

// AgentProfile holds the rich visual character profile generated by the world-builder LLM step.
type AgentProfile struct {
	Name            string   `json:"name"`
	Mood            string   `json:"mood"`
	RolePurpose     string   `json:"role_purpose"`
	PrimaryColor    string   `json:"primary_color"`
	SecondaryColor  string   `json:"secondary_color"`
	TabletGlowColor string   `json:"tablet_glow_color"`
	Characteristics []string `json:"characteristics"`
}

var charTypeStyles = map[string]string{
	"wizard":     "medieval fantasy wizard, deep purple robes, tall pointed hat, crystal-topped staff, arcane runes glowing",
	"strategist": "medieval fantasy knight commander, crimson cloak over plate armor, golden war medals, commanding pose",
	"oracle":     "medieval fantasy mystic seer, flowing amber robes, glowing crystal orb, astrolabe instruments",
	"guardian":   "medieval fantasy armored knight, heavy steel plate armor, tower shield, castle battlements behind",
	"artisan":    "medieval fantasy master craftsman, leather apron over fine tunic, woodcarving tools, workshop setting",
	"bard":       "medieval fantasy bard troubadour, emerald green travelling cloak, ornate lute, tavern warmth",
	"scholar":    "medieval fantasy monk scholar, brown monastic robes, round spectacles, candle-lit scriptorium",
	"merchant":   "medieval fantasy guild merchant, gold-trimmed doublet, feathered cap, market stall with wares",
}

const avatarPrompt = `Single character on a solid flat magenta backdrop (#FF00FF). ` +
	`The entire backdrop must be uniform bright magenta with no gradients, no scenery, no patterns. ` +
	`The magenta color extends to every pixel of all four edges of the image with no margin, no border, no frame. ` +
	`Upper-body depiction from the belly upward, centered in the image, square 1:1 composition. ` +
	`The character's head may be slightly cropped by the top edge of the image. ` +
	`Detailed 2D medieval fantasy character, clean digital painting style with defined edges, warm rich colors. ` +
	`The character fills most of the image vertically. Arms close to the body, held items overlap the torso, compact silhouette. ` +
	`Outfit color: %s with %s trim and accents. ` +
	`Head: %s. Attire: %s. %s. ` +
	`A soft %s magical glow emanates from their hands. Holds %s. ` +
	`The character must have a thin dark ink outline along all edges of their silhouette, separating them clearly from the magenta backdrop. ` +
	`The character should avoid using bright magenta (#FF00FF) as a primary clothing color, but may freely include pink, rose, fuchsia, or purple tones in accents, effects, and details. ` +
	`No text, letters, numbers, words, or symbols anywhere in the image.`

var (
	poseVariants = []string{
		"three-quarter view facing left",
		"three-quarter view facing right",
		"looking slightly upward with confidence",
		"gazing to the side thoughtfully",
		"facing forward with a determined expression",
		"turned slightly with a mysterious half-smile",
	}
	lightingVariants = []string{
		"warm candlelight from the left side",
		"cool moonlight from above",
		"dramatic side lighting with deep shadows",
		"soft diffused golden light",
		"backlit with a warm ambient rim light",
		"overhead lantern light with soft shadows below",
	}
	expressionVariants = []string{
		"confident and commanding",
		"wise and contemplative",
		"fierce and battle-ready",
		"serene and all-knowing",
		"cunning with a subtle smirk",
		"noble and dignified",
		"mysterious and enigmatic",
		"warm and approachable",
	}
)

// BuildAvatarPrompt constructs the full avatar image prompt from an AgentProfile.
func BuildAvatarPrompt(profile *AgentProfile) string {
	headwear, outfit, uniqueFeature, heldItem := extractCharacteristics(profile.Characteristics)

	pose := poseVariants[rand.Intn(len(poseVariants))]
	lighting := lightingVariants[rand.Intn(len(lightingVariants))]
	expression := expressionVariants[rand.Intn(len(expressionVariants))]

	base := fmt.Sprintf(avatarPrompt,
		profile.PrimaryColor,
		profile.SecondaryColor,
		headwear,
		outfit,
		uniqueFeature,
		profile.TabletGlowColor,
		heldItem,
	)
	return base + fmt.Sprintf(" Character pose: %s. Expression: %s. Lighting: %s.", pose, expression, lighting)
}

// GeminiService handles all Gemini API calls (analysis + image generation).
type GeminiService struct {
	apiKey     string
	httpClient *http.Client
}

// NewGeminiService creates a Gemini service.
func NewGeminiService(apiKey string) *GeminiService {
	return &GeminiService{
		apiKey:     apiKey,
		httpClient: &http.Client{Timeout: 45 * time.Second},
	}
}

// AnalyzePrompt sends the agent prompt to Gemini Flash and returns structured metadata.
func (g *GeminiService) AnalyzePrompt(prompt string) (*PromptAnalysis, error) {
	if g.apiKey == "" {
		return nil, fmt.Errorf("gemini api key not configured")
	}

	desc := prompt
	if len(desc) > 600 {
		desc = desc[:600]
	}

	instruction := fmt.Sprintf(`Classify this AI agent prompt. Return ONLY valid JSON:
{
  "character_type": "<wizard|strategist|oracle|guardian|artisan|bard|scholar|merchant>",
  "subclass": "<see mapping>",
  "category": "<backend|frontend|data|security|creative|business|research|general>",
  "tags": ["<3-5 lowercase/hyphenated tags>"],
  "rarity": "<common|uncommon|rare|epic|legendary>",
  "image_prompt": "<1-2 sentence pixel art portrait description>"
}

Type->subclasses: wizard(archmage,sorcerer,hex_master) strategist(war_commander,tactician,diplomat) oracle(prophet,analyst,seer) guardian(sentinel,warden,paladin) artisan(sculptor,weaver,painter) bard(storyteller,lyricist,chronicler) scholar(sage,professor,librarian) merchant(entrepreneur,trader,ambassador)

Type hints: wizard=code/backend, strategist=planning/PM, oracle=data/ML, guardian=security/infra, artisan=frontend/design, bard=writing/creative, scholar=research/education, merchant=business/marketing

Rarity: common(<80chars,generic) uncommon(somewhat specific) rare(detailed+personality) epic(very detailed,specific tools) legendary(>400chars,complex,multi-role)

Agent prompt: %s`, desc)

	url := fmt.Sprintf("%s/models/%s:generateContent", geminiBase, flashModel)

	reqBody := map[string]any{
		"contents": []map[string]any{
			{"parts": []map[string]string{{"text": instruction}}},
		},
		"generationConfig": map[string]any{
			"temperature": 0.4,
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gemini analyze error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, fmt.Errorf("decode analyze response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("empty analyze response from gemini")
	}

	text := strings.TrimSpace(apiResp.Candidates[0].Content.Parts[0].Text)
	text = strings.TrimPrefix(text, "```json")
	text = strings.TrimPrefix(text, "```")
	text = strings.TrimSuffix(text, "```")
	text = strings.TrimSpace(text)

	var analysis PromptAnalysis
	if err := json.Unmarshal([]byte(text), &analysis); err != nil {
		return nil, fmt.Errorf("parse analysis JSON: %w - raw: %s", err, text)
	}
	analysis = sanitizeAnalysis(analysis)
	return &analysis, nil
}

// GenerateAgentProfile calls Gemini Flash to generate a rich visual character profile.
func (g *GeminiService) GenerateAgentProfile(agentConcept string) (*AgentProfile, error) {
	if g.apiKey == "" {
		return nil, fmt.Errorf("gemini api key not configured")
	}

	concept := agentConcept
	if len(concept) > 400 {
		concept = concept[:400]
	}

	instruction := fmt.Sprintf(`You are a medieval fantasy world-builder. Given an AI agent concept, create a unique character who embodies that agent's purpose as a medieval fantasy archetype.

Concept: %s

Return ONLY valid JSON matching this schema:
{
  "name": "A medieval fantasy character name reflecting the agent's purpose",
  "mood": "The character's emotional bearing in 2-4 words",
  "role_purpose": "One sentence describing what this character does in the medieval world",
  "primary_color": "Main outfit color using rich medieval tones. No neon or cyber colors.",
  "secondary_color": "Accent/trim color that complements the primary. No neon.",
  "tablet_glow_color": "Color of the character's magical aura or enchanted glow",
  "characteristics": [
    "Headwear or facial feature: a specific descriptive phrase",
    "Outfit detail: a specific descriptive phrase",
    "Unique distinguishing visual feature: something memorable",
    "Held item: the primary object the character carries"
  ]
}

Rules:
- The character MUST feel like a medieval fantasy figure
- Colors must be natural, rich, period-appropriate
- Each characteristic must be a vivid descriptive phrase (8-20 words)
- The character should clearly reflect the AI agent's actual domain and purpose`, concept)

	url := fmt.Sprintf("%s/models/%s:generateContent", geminiBase, flashModel)

	reqBody := map[string]any{
		"contents": []map[string]any{
			{"parts": []map[string]string{{"text": instruction}}},
		},
		"generationConfig": map[string]any{
			"temperature":      0.7,
			"response_mime_type": "application/json",
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("gemini profile request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gemini profile error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, fmt.Errorf("decode profile response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("empty profile response from gemini")
	}

	rawJSON := apiResp.Candidates[0].Content.Parts[0].Text
	var profile AgentProfile
	if err := json.Unmarshal([]byte(rawJSON), &profile); err != nil {
		return nil, fmt.Errorf("parse profile JSON: %w", err)
	}
	return &profile, nil
}

// GenerateAvatarImage generates a medieval fantasy avatar using Imagen.
func (g *GeminiService) GenerateAvatarImage(profile *AgentProfile) (string, error) {
	return g.callImagen("Game character asset, " + BuildAvatarPrompt(profile))
}

func (g *GeminiService) callImagen(prompt string) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("gemini api key not configured")
	}
	url := fmt.Sprintf("%s/models/%s:predict", geminiBase, imagenModel)

	reqBody := map[string]any{
		"instances": []map[string]any{
			{"prompt": prompt},
		},
		"parameters": map[string]any{
			"sampleCount":      1,
			"aspectRatio":      "1:1",
			"personGeneration": "ALLOW_ADULT",
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("imagen request: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("imagen error %d: %s", resp.StatusCode, string(respBody))
	}

	var imgResp struct {
		Predictions []struct {
			BytesBase64Encoded string `json:"bytesBase64Encoded"`
			MimeType           string `json:"mimeType"`
		} `json:"predictions"`
	}
	if err := json.Unmarshal(respBody, &imgResp); err != nil {
		return "", fmt.Errorf("parse imagen response: %w", err)
	}
	if len(imgResp.Predictions) == 0 || imgResp.Predictions[0].BytesBase64Encoded == "" {
		return "", fmt.Errorf("no image in imagen response (likely safety filter triggered)")
	}
	return imgResp.Predictions[0].BytesBase64Encoded, nil
}

// GenerateImage calls Imagen with a style prefix for the given character type.
func (g *GeminiService) GenerateImage(imagePrompt, charType string) (string, error) {
	style := charTypeStyles[charType]
	if style == "" {
		style = "medieval fantasy character, rich painterly illustration"
	}
	fullPrompt := style + ". " + imagePrompt +
		" Style: detailed 2D medieval fantasy illustration, warm painterly tones, " +
		"storybook RPG art, centered character, contextual background, " +
		"no text, no watermark, square composition."
	return g.callImagen(fullPrompt)
}

// Chat sends a user message to Gemini Flash with a system instruction.
func (g *GeminiService) Chat(systemPrompt, userMessage string) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("gemini api key not configured")
	}

	url := fmt.Sprintf("%s/models/%s:generateContent", geminiBase, flashModel)

	reqBody := map[string]any{
		"systemInstruction": map[string]any{
			"parts": []map[string]string{{"text": systemPrompt}},
		},
		"contents": []map[string]any{
			{
				"role":  "user",
				"parts": []map[string]string{{"text": userMessage}},
			},
		},
		"generationConfig": map[string]any{
			"maxOutputTokens": 1024,
			"temperature":     0.8,
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("gemini chat request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("gemini chat error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return "", fmt.Errorf("decode chat response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("empty chat response from gemini")
	}
	return strings.TrimSpace(apiResp.Candidates[0].Content.Parts[0].Text), nil
}

func sanitizeAnalysis(a PromptAnalysis) PromptAnalysis {
	validTypes := map[string]bool{
		"wizard": true, "strategist": true, "oracle": true, "guardian": true,
		"artisan": true, "bard": true, "scholar": true, "merchant": true,
	}
	validCategories := map[string]bool{
		"backend": true, "frontend": true, "data": true, "security": true,
		"creative": true, "business": true, "research": true, "general": true,
	}
	validRarities := map[string]bool{
		"common": true, "uncommon": true, "rare": true, "epic": true, "legendary": true,
	}

	a.CharacterType = strings.ToLower(strings.TrimSpace(a.CharacterType))
	if !validTypes[a.CharacterType] {
		a.CharacterType = "wizard"
	}
	a.Category = strings.ToLower(strings.TrimSpace(a.Category))
	if !validCategories[a.Category] {
		a.Category = "general"
	}
	a.Rarity = strings.ToLower(strings.TrimSpace(a.Rarity))
	if !validRarities[a.Rarity] {
		a.Rarity = "common"
	}
	if len(a.Tags) == 0 {
		a.Tags = []string{a.Category}
	}
	if len(a.Tags) > 5 {
		a.Tags = a.Tags[:5]
	}
	if a.Subclass == "" {
		a.Subclass = defaultSubclass[a.CharacterType]
	}
	return a
}

func sanitizeProfile(p AgentProfile) AgentProfile {
	if p.PrimaryColor == "" {
		p.PrimaryColor = "Royal Purple"
	}
	if p.SecondaryColor == "" {
		p.SecondaryColor = "Burnished Gold"
	}
	if p.TabletGlowColor == "" {
		p.TabletGlowColor = "Amber"
	}
	if len(p.Characteristics) < 4 {
		defaults := []string{
			"a deep hood casting shadow over a weathered but wise face",
			"layered travelling robes with a leather belt and iron buckle",
			"faint arcane runes drifting in the air around the shoulders",
			"a gnarled oak staff topped with a softly glowing crystal",
		}
		for len(p.Characteristics) < 4 {
			p.Characteristics = append(p.Characteristics, defaults[len(p.Characteristics)])
		}
	}
	return p
}

func extractCharacteristics(chars []string) (headwear, outfit, uniqueFeature, heldItem string) {
	get := func(i int, fallback string) string {
		if i >= len(chars) {
			return fallback
		}
		s := strings.TrimSpace(chars[i])
		for len(s) > 0 {
			if s[0] >= '0' && s[0] <= '9' {
				j := 0
				for j < len(s) && s[j] >= '0' && s[j] <= '9' {
					j++
				}
				if j < len(s) && (s[j] == '.' || s[j] == ')') {
					rest := s[j+1:]
					s = strings.TrimSpace(rest)
					continue
				}
			}
			if strings.HasPrefix(s, "- ") || strings.HasPrefix(s, "* ") {
				s = strings.TrimSpace(s[2:])
				continue
			}
			break
		}
		if s == "" {
			return fallback
		}
		return s
	}
	headwear = get(0, "a deep hood casting shadow over a weathered but wise face")
	outfit = get(1, "layered travelling robes with a leather belt and iron buckle")
	uniqueFeature = get(2, "faint arcane runes drifting in the air around the shoulders")
	heldItem = get(3, "a gnarled oak staff topped with a softly glowing crystal")
	return
}
