// lib/features/agent_detail/widgets/export_agent_widget.dart

import 'dart:js_interop';
import 'package:web/web.dart' as web;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../app/theme.dart';
import '../../../shared/models/agent_model.dart';

/// "Use This Agent" export section — download as CLAUDE.md, .cursorrules, or copy prompt.
/// Safety: returns SizedBox.shrink() if the prompt is empty (non-owner fallback).
class ExportAgentWidget extends StatelessWidget {
  final AgentModel agent;
  const ExportAgentWidget({super.key, required this.agent});

  // ── File content builders ─────────────────────────────────────────────────

  String _buildClaudeMd() {
    final url = '${web.window.location.origin}/agent/${agent.id}';
    final buf = StringBuffer()
      ..writeln('# ${agent.title}')
      ..writeln()
      ..writeln('> ${agent.description}')
      ..writeln('> Generated by Agent Store — $url')
      ..writeln()
      ..write(agent.prompt);
    return buf.toString();
  }

  String _buildCursorRules() => agent.prompt;

  // ── Download helper ───────────────────────────────────────────────────────

  void _downloadFile(String content, String filename) {
    final blob = web.Blob(
      [content.toJS].toJS,
      web.BlobPropertyBag(type: 'text/plain'),
    );
    final url = web.URL.createObjectURL(blob);
    final anchor = web.document.createElement('a') as web.HTMLAnchorElement;
    anchor.href = url;
    anchor.download = filename;
    anchor.click();
    web.URL.revokeObjectURL(url);
  }

  // ── Actions ───────────────────────────────────────────────────────────────

  void _exportClaudeCode() {
    _downloadFile(_buildClaudeMd(), 'CLAUDE.md');
  }

  void _exportCursor() {
    _downloadFile(_buildCursorRules(), '.cursorrules');
  }

  Future<void> _copyPrompt(BuildContext context) async {
    await Clipboard.setData(ClipboardData(text: agent.prompt));
    if (context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Row(mainAxisSize: MainAxisSize.min, children: [
          Icon(Icons.check_circle, color: AppTheme.olive, size: 16),
          SizedBox(width: 8),
          Text('Prompt copied to clipboard'),
        ]),
        duration: Duration(seconds: 2),
      ));
    }
  }

  // ── Build ─────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    // Safety guard: if prompt is empty (backend returns empty for non-owners),
    // don't render the export widget at all.
    if (agent.prompt.isEmpty) return const SizedBox.shrink();

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppTheme.card,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          const Row(children: [
            Icon(Icons.terminal_rounded, color: AppTheme.gold, size: 18),
            SizedBox(width: 8),
            Text(
              'Use This Agent',
              style: TextStyle(
                color: AppTheme.textH,
                fontSize: 15,
                fontWeight: FontWeight.bold,
              ),
            ),
          ]),
          const SizedBox(height: 6),
          const Text(
            'Export this prompt for your favourite AI coding tool.',
            style: TextStyle(color: AppTheme.textM, fontSize: 12, height: 1.4),
          ),
          const SizedBox(height: 16),

          // Buttons row — wraps on narrow screens
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: [
              _ExportPillButton(
                label: 'Claude Code',
                subtitle: 'CLAUDE.md',
                icon: Icons.terminal_rounded,
                accentColor: const Color(0xFF9B6DFF),
                onPressed: _exportClaudeCode,
                tooltip: 'Download CLAUDE.md',
              ),
              _ExportPillButton(
                label: 'Cursor',
                subtitle: '.cursorrules',
                icon: Icons.edit_note_rounded,
                accentColor: const Color(0xFF3B9EFF),
                onPressed: _exportCursor,
                tooltip: 'Download .cursorrules',
              ),
              _ExportPillButton(
                label: 'Copy Prompt',
                subtitle: 'clipboard',
                icon: Icons.content_copy_rounded,
                accentColor: AppTheme.textM,
                onPressed: () => _copyPrompt(context),
                tooltip: 'Copy raw prompt to clipboard',
              ),
            ],
          ),
        ],
      ),
    );
  }
}

/// Pill-shaped export button with icon on left, text + subtitle on right, and hover state.
class _ExportPillButton extends StatefulWidget {
  final String label;
  final String subtitle;
  final IconData icon;
  final Color accentColor;
  final VoidCallback onPressed;
  final String tooltip;

  const _ExportPillButton({
    required this.label,
    required this.subtitle,
    required this.icon,
    required this.accentColor,
    required this.onPressed,
    required this.tooltip,
  });

  @override
  State<_ExportPillButton> createState() => _ExportPillButtonState();
}

class _ExportPillButtonState extends State<_ExportPillButton> {
  bool _hovered = false;

  @override
  Widget build(BuildContext context) {
    return Tooltip(
      message: widget.tooltip,
      child: MouseRegion(
        onEnter: (_) => setState(() => _hovered = true),
        onExit: (_) => setState(() => _hovered = false),
        cursor: SystemMouseCursors.click,
        child: GestureDetector(
          onTap: widget.onPressed,
          child: AnimatedContainer(
            duration: const Duration(milliseconds: 200),
            padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 10),
            decoration: BoxDecoration(
              color: _hovered
                  ? widget.accentColor.withValues(alpha: 0.18)
                  : AppTheme.card2,
              borderRadius: BorderRadius.circular(24),
              border: Border.all(
                color: _hovered
                    ? widget.accentColor.withValues(alpha: 0.6)
                    : AppTheme.border,
                width: _hovered ? 1.5 : 1.0,
              ),
              boxShadow: _hovered
                  ? [
                      BoxShadow(
                        color: widget.accentColor.withValues(alpha: 0.15),
                        blurRadius: 8,
                        spreadRadius: 1,
                      ),
                    ]
                  : null,
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(widget.icon, size: 16, color: widget.accentColor),
                const SizedBox(width: 8),
                Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      widget.label,
                      style: TextStyle(
                        color: _hovered ? widget.accentColor : AppTheme.textB,
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    Text(
                      widget.subtitle,
                      style: TextStyle(
                        color: _hovered
                            ? widget.accentColor.withValues(alpha: 0.7)
                            : AppTheme.textM,
                        fontSize: 10,
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
