import 'dart:convert';
import '../../features/character/character_types.dart';

class AgentModel {
  final int id;
  final String title;
  final String description;
  final String prompt;
  final String category;
  final String creatorWallet;
  final CharacterType characterType;
  final CharacterSubclass subclass;
  final CharacterRarity rarity;
  final Map<String, int> stats;
  final List<String> traits;
  final List<String> tags;
  final int useCount;
  final int saveCount;
  final double price;
  final DateTime createdAt;
  /// Base64-encoded PNG generated by Gemini Imagen. null = show pixel art fallback.
  final String? generatedImage;
  /// Relative URL to the server-hosted image (e.g. "/api/v1/images/agents/123.webp").
  /// Preferred over [generatedImage] when available; base64 is the fallback.
  final String? imageUrl;
  /// Character mood generated by the world-builder LLM step (from character_data.profile.mood).
  final String? profileMood;
  /// Role/purpose summary from the world-builder LLM step (from character_data.profile.role_purpose).
  final String? profileRolePurpose;
  /// Card layout version: "1.0" for legacy, "2.0" for new background+portrait layout.
  final String cardVersion;
  /// Prompt quality score (0-100) assigned by the analysis pipeline.
  final int promptScore;
  /// One-line description of what the agent does (generated by analysis).
  final String? serviceDescription;
  /// Whether the current user owns this agent (creator or purchased).
  final bool owned;

  const AgentModel({
    required this.id,
    required this.title,
    required this.description,
    required this.prompt,
    required this.category,
    required this.creatorWallet,
    required this.characterType,
    required this.subclass,
    required this.rarity,
    required this.stats,
    required this.traits,
    required this.tags,
    required this.useCount,
    required this.saveCount,
    required this.price,
    required this.createdAt,
    this.generatedImage,
    this.imageUrl,
    this.profileMood,
    this.profileRolePurpose,
    this.cardVersion = '1.0',
    this.promptScore = 0,
    this.serviceDescription,
    this.owned = false,
  });

  AgentModel copyWith({
    int? id,
    String? title,
    String? description,
    String? prompt,
    String? category,
    String? creatorWallet,
    CharacterType? characterType,
    CharacterSubclass? subclass,
    CharacterRarity? rarity,
    Map<String, int>? stats,
    List<String>? traits,
    List<String>? tags,
    int? useCount,
    int? saveCount,
    double? price,
    DateTime? createdAt,
    String? generatedImage,
    String? imageUrl,
    String? profileMood,
    String? profileRolePurpose,
    String? cardVersion,
    int? promptScore,
    String? serviceDescription,
    bool? owned,
  }) =>
      AgentModel(
        id: id ?? this.id,
        title: title ?? this.title,
        description: description ?? this.description,
        prompt: prompt ?? this.prompt,
        category: category ?? this.category,
        creatorWallet: creatorWallet ?? this.creatorWallet,
        characterType: characterType ?? this.characterType,
        subclass: subclass ?? this.subclass,
        rarity: rarity ?? this.rarity,
        stats: stats ?? this.stats,
        traits: traits ?? this.traits,
        tags: tags ?? this.tags,
        useCount: useCount ?? this.useCount,
        saveCount: saveCount ?? this.saveCount,
        price: price ?? this.price,
        createdAt: createdAt ?? this.createdAt,
        generatedImage: generatedImage ?? this.generatedImage,
        imageUrl: imageUrl ?? this.imageUrl,
        profileMood: profileMood ?? this.profileMood,
        profileRolePurpose: profileRolePurpose ?? this.profileRolePurpose,
        cardVersion: cardVersion ?? this.cardVersion,
        promptScore: promptScore ?? this.promptScore,
        serviceDescription: serviceDescription ?? this.serviceDescription,
        owned: owned ?? this.owned,
      );

  factory AgentModel.fromJson(Map<String, dynamic> json) {
    final rawData = json['character_data'];
    Map<String, dynamic> charData;
    if (rawData is String && rawData.isNotEmpty) {
      try {
        charData = jsonDecode(rawData) as Map<String, dynamic>? ?? {};
      } catch (_) {
        charData = {};
      }
    } else if (rawData is Map<String, dynamic>) {
      charData = rawData;
    } else {
      charData = {};
    }

    final rawStats = charData['stats'] as Map<String, dynamic>? ?? {};
    final stats = rawStats.map((k, v) => MapEntry(k, (v as num).toInt()));

    final rawTraits = charData['traits'] as List<dynamic>? ?? [];

    // Parse AgentProfile nested inside character_data["profile"] (added in v2.6 image pipeline).
    final rawProfile = charData['profile'];
    Map<String, dynamic> profileMap = {};
    if (rawProfile is Map<String, dynamic>) {
      profileMap = rawProfile;
    } else if (rawProfile is String && rawProfile.isNotEmpty) {
      try {
        profileMap = jsonDecode(rawProfile) as Map<String, dynamic>? ?? {};
      } catch (_) {}
    }
    final profileMood = profileMap['mood'] as String?;
    final profileRolePurpose = profileMap['role_purpose'] as String?;

    final subclassRaw =
        (json['subclass'] as String?)?.isNotEmpty == true
            ? json['subclass'] as String
            : (charData['subclass'] as String? ?? '');

    // generated_image comes directly from the agent JSON field
    final generatedImage = json['generated_image'] as String?;
    // Relative URL to the server-hosted image (preferred over base64)
    final imageUrl = json['image_url'] as String?;

    return AgentModel(
      id:             (json['id'] as num?)?.toInt() ?? 0,
      title:          json['title'] as String? ?? '',
      description:    json['description'] as String? ?? '',
      prompt:         json['prompt'] as String? ?? '',
      category:       json['category'] as String? ?? '',
      creatorWallet:  json['creator_wallet'] as String? ?? '',
      characterType:  characterTypeFromString(json['character_type'] as String? ?? ''),
      subclass:       subclassFromString(subclassRaw),
      rarity:         CharacterRarityExt.fromString(json['rarity'] as String? ?? 'common'),
      stats:          stats,
      traits:         rawTraits.map((e) => e.toString()).toList(),
      tags:           (json['tags'] as List<dynamic>? ?? []).map((e) => e.toString()).toList(),
      useCount:       (json['use_count'] as num?)?.toInt() ?? 0,
      saveCount:      (json['save_count'] as num?)?.toInt() ?? 0,
      price:             (json['price'] as num?)?.toDouble() ?? 0.0,
      createdAt:         DateTime.tryParse(json['created_at'] as String? ?? '') ?? DateTime.now(),
      generatedImage:    (generatedImage != null && generatedImage.isNotEmpty) ? generatedImage : null,
      imageUrl:          (imageUrl != null && imageUrl.isNotEmpty) ? imageUrl : null,
      profileMood:       (profileMood?.isNotEmpty == true) ? profileMood : null,
      profileRolePurpose:(profileRolePurpose?.isNotEmpty == true) ? profileRolePurpose : null,
      cardVersion:       json['card_version'] as String? ?? '1.0',
      promptScore:       (json['prompt_score'] as num?)?.toInt() ?? 0,
      serviceDescription: json['service_description'] as String?,
      owned:             json['owned'] as bool? ?? false,
    );
  }
}
