package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"math/rand"
	"net/http"
	"strings"
	"time"
)

const (
	geminiBase  = "https://generativelanguage.googleapis.com/v1beta"
	flashModel  = "gemini-2.5-flash"
	imagenModel = "imagen-4.0-fast-generate-001"
)

// PromptAnalysis holds the structured result of Gemini's prompt analysis.
type PromptAnalysis struct {
	CharacterType string   `json:"character_type"`
	Subclass      string   `json:"subclass"`
	Category      string   `json:"category"`
	Tags          []string `json:"tags"`
	Rarity        string   `json:"rarity"`
	ImagePrompt   string   `json:"image_prompt"`
}

// AgentProfile holds the rich visual character profile generated by the world-builder LLM step.
// It drives both display metadata and the medieval fantasy image prompt for Step 2.
type AgentProfile struct {
	Name            string   `json:"name"`
	Mood            string   `json:"mood"`
	RolePurpose     string   `json:"role_purpose"`
	PrimaryColor    string   `json:"primary_color"`
	SecondaryColor  string   `json:"secondary_color"`
	TabletGlowColor string   `json:"tablet_glow_color"`
	Characteristics []string `json:"characteristics"`
}

// charTypeStyles provides the visual base for each character type's image prompt.
var charTypeStyles = map[string]string{
	"wizard":     "medieval fantasy wizard, deep purple robes, tall pointed hat, crystal-topped staff, arcane runes glowing",
	"strategist": "medieval fantasy knight commander, crimson cloak over plate armor, golden war medals, commanding pose",
	"oracle":     "medieval fantasy mystic seer, flowing amber robes, glowing crystal orb, astrolabe instruments",
	"guardian":   "medieval fantasy armored knight, heavy steel plate armor, tower shield, castle battlements behind",
	"artisan":    "medieval fantasy master craftsman, leather apron over fine tunic, woodcarving tools, workshop setting",
	"bard":       "medieval fantasy bard troubadour, emerald green travelling cloak, ornate lute, tavern warmth",
	"scholar":    "medieval fantasy monk scholar, brown monastic robes, round spectacles, candle-lit scriptorium",
	"merchant":   "medieval fantasy guild merchant, gold-trimmed doublet, feathered cap, market stall with wares",
}

// avatarPrompt is the shared prompt template for medieval fantasy avatar generation.
// Uses 7 %s placeholders: PrimaryColor, SecondaryColor, headwear, outfit, uniqueFeature, glowColor, heldItem.
//
// Design notes (chroma key + frame elimination optimized):
// - Background/composition instructions front-loaded for maximum model attention
// - Magenta (#FF00FF) background: zero overlap with any character type color palette
// - Edge-bleed instruction makes frames structurally impossible
// - "portrait"/"illustration" removed (top frame-triggering words in training data)
// - "backdrop" instead of "background" avoids canvas/mat-board framing associations
const avatarPrompt = `Single character on a solid flat magenta backdrop (#FF00FF). ` +
	`The entire backdrop must be uniform bright magenta with no gradients, no scenery, no patterns. ` +
	`The magenta color extends to every pixel of all four edges of the image with no margin, no border, no frame. ` +
	`Upper-body depiction from the belly upward, centered in the image, square 1:1 composition. ` +
	`The character's head may be slightly cropped by the top edge of the image. ` +
	`Detailed 2D medieval fantasy character, clean digital painting style with defined edges, warm rich colors. ` +
	`The character fills most of the image vertically. Arms close to the body, held items overlap the torso, compact silhouette. ` +
	`Outfit color: %s with %s trim and accents. ` +
	`Head: %s. Attire: %s. %s. ` +
	`A soft %s magical glow emanates from their hands. Holds %s. ` +
	`The character must have a thin dark ink outline along all edges of their silhouette, separating them clearly from the magenta backdrop. ` +
	`The character should avoid using bright magenta (#FF00FF) as a primary clothing color, but may freely include pink, rose, fuchsia, or purple tones in accents, effects, and details. ` +
	`No text, letters, numbers, words, or symbols anywhere in the image.`

// Randomized prompt modifiers to ensure visual diversity across generated characters.
// Since Imagen does not support a seed parameter, we inject random variety into the prompt text itself.
var (
	poseVariants = []string{
		"three-quarter view facing left",
		"three-quarter view facing right",
		"looking slightly upward with confidence",
		"gazing to the side thoughtfully",
		"facing forward with a determined expression",
		"turned slightly with a mysterious half-smile",
	}
	lightingVariants = []string{
		"warm candlelight from the left side",
		"cool moonlight from above",
		"dramatic side lighting with deep shadows",
		"soft diffused golden light",
		"backlit with a warm ambient rim light",
		"overhead lantern light with soft shadows below",
	}
	expressionVariants = []string{
		"confident and commanding",
		"wise and contemplative",
		"fierce and battle-ready",
		"serene and all-knowing",
		"cunning with a subtle smirk",
		"noble and dignified",
		"mysterious and enigmatic",
		"warm and approachable",
	}
)

// BuildAvatarPrompt constructs the full avatar image prompt from an AgentProfile using the shared template.
// Exported so pollinations_service.go can reuse it without duplicating the prompt.
// Injects randomized pose, lighting, and expression modifiers to ensure visual diversity.
func BuildAvatarPrompt(profile *AgentProfile) string {
	headwear, outfit, uniqueFeature, heldItem := extractCharacteristics(profile.Characteristics)

	pose := poseVariants[rand.Intn(len(poseVariants))]
	lighting := lightingVariants[rand.Intn(len(lightingVariants))]
	expression := expressionVariants[rand.Intn(len(expressionVariants))]

	base := fmt.Sprintf(avatarPrompt,
		profile.PrimaryColor,
		profile.SecondaryColor,
		headwear,
		outfit,
		uniqueFeature,
		profile.TabletGlowColor,
		heldItem,
	)

	// Append randomized modifiers for visual diversity
	return base + fmt.Sprintf(" Character pose: %s. Expression: %s. Lighting: %s.", pose, expression, lighting)
}

// GeminiService handles all Gemini API calls (analysis + image generation).
type GeminiService struct {
	apiKey     string
	httpClient *http.Client
}

func NewGeminiService(apiKey string) *GeminiService {
	return &GeminiService{
		apiKey: apiKey,
		httpClient: &http.Client{
			Timeout: 45 * time.Second,
		},
	}
}

// AnalyzePrompt sends the agent prompt to Gemini Flash and returns structured metadata.
func (g *GeminiService) AnalyzePrompt(prompt string) (*PromptAnalysis, error) {
	if g.apiKey == "" {
		return nil, fmt.Errorf("gemini api key not configured")
	}

	desc := prompt
	if len(desc) > 600 {
		desc = desc[:600]
	}

	instruction := fmt.Sprintf(`Classify this AI agent prompt. Return ONLY valid JSON:
{
  "character_type": "<wizard|strategist|oracle|guardian|artisan|bard|scholar|merchant>",
  "subclass": "<see mapping>",
  "category": "<backend|frontend|data|security|creative|business|research|general>",
  "tags": ["<3-5 lowercase/hyphenated tags>"],
  "rarity": "<common|uncommon|rare|epic|legendary>",
  "image_prompt": "<1-2 sentence pixel art portrait description>"
}

Type->subclasses: wizard(archmage,sorcerer,hex_master) strategist(war_commander,tactician,diplomat) oracle(prophet,analyst,seer) guardian(sentinel,warden,paladin) artisan(sculptor,weaver,painter) bard(storyteller,lyricist,chronicler) scholar(sage,professor,librarian) merchant(entrepreneur,trader,ambassador)

Type hints: wizard=code/backend, strategist=planning/PM, oracle=data/ML, guardian=security/infra, artisan=frontend/design, bard=writing/creative, scholar=research/education, merchant=business/marketing

Rarity: common(<80chars,generic) uncommon(somewhat specific) rare(detailed+personality) epic(very detailed,specific tools) legendary(>400chars,complex,multi-role)

Agent prompt: %s`, desc)

	url := fmt.Sprintf("%s/models/%s:generateContent", geminiBase, flashModel)

	reqBody := map[string]interface{}{
		"contents": []map[string]interface{}{
			{"parts": []map[string]string{{"text": instruction}}},
		},
		"generationConfig": map[string]interface{}{
			"temperature": 0.4,
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gemini analyze error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, fmt.Errorf("decode analyze response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("empty analyze response from gemini")
	}

	text := strings.TrimSpace(apiResp.Candidates[0].Content.Parts[0].Text)
	// Strip markdown fences if present
	text = strings.TrimPrefix(text, "```json")
	text = strings.TrimPrefix(text, "```")
	text = strings.TrimSuffix(text, "```")
	text = strings.TrimSpace(text)

	var analysis PromptAnalysis
	if err := json.Unmarshal([]byte(text), &analysis); err != nil {
		return nil, fmt.Errorf("parse analysis JSON: %w — raw: %s", err, text)
	}

	// Validate and sanitize
	analysis = sanitizeAnalysis(analysis)
	return &analysis, nil
}

// GenerateAgentProfile calls Gemini Flash with a world-builder prompt to generate a rich,
// cohesive visual character profile for the given agent concept. The profile drives Step 2
// (pixel-art avatar generation) and is stored alongside the agent's stats in character_data.
func (g *GeminiService) GenerateAgentProfile(agentConcept string) (*AgentProfile, error) {
	if g.apiKey == "" {
		return nil, fmt.Errorf("gemini api key not configured")
	}

	concept := agentConcept
	if len(concept) > 400 {
		concept = concept[:400]
	}

	instruction := fmt.Sprintf(`You are a medieval fantasy world-builder. Given an AI agent concept, create a unique character who embodies that agent's purpose as a medieval fantasy archetype.

Concept: %s

Return ONLY valid JSON matching this schema:
{
  "name": "A medieval fantasy character name reflecting the agent's purpose (e.g. 'Brother Aldric the Chronicler')",
  "mood": "The character's emotional bearing in 2-4 words (e.g. 'Calm and watchful', 'Fierce and resolute')",
  "role_purpose": "One sentence describing what this character does in the medieval world, mapped from the AI agent's actual purpose",
  "primary_color": "Main outfit color using rich medieval tones (e.g. 'Deep Crimson', 'Forest Green', 'Royal Purple'). No neon or cyber colors.",
  "secondary_color": "Accent/trim color that complements the primary (e.g. 'Burnished Gold', 'Silver', 'Ivory'). No neon.",
  "tablet_glow_color": "Color of the character's magical aura or enchanted glow (e.g. 'Amber', 'Sapphire Blue', 'Emerald')",
  "characteristics": [
    "Headwear or facial feature: a specific descriptive phrase (e.g. 'a weathered leather hood with owl-feather trim', 'a steel helm with raised visor revealing kind eyes', 'round brass spectacles perched on a lined face')",
    "Outfit detail: a specific descriptive phrase (e.g. 'ink-stained scholar robes with brass clasps', 'battle-worn plate armor with a crimson surcoat', 'a finely embroidered merchant doublet with pearl buttons')",
    "Unique distinguishing visual feature: something memorable that sets this character apart (e.g. 'a small translucent fairy companion hovering at the shoulder', 'floating constellation charts orbiting overhead', 'a loyal falcon perched on the forearm')",
    "Held item: the primary object the character carries, reflecting purpose (e.g. 'an ancient leather-bound grimoire with glowing runes', 'a broadsword with a lion-head pommel', 'a brass astrolabe and rolled star chart')"
  ]
}

Rules:
- The character MUST feel like a medieval fantasy figure (wizard, knight, alchemist, monk, bard, merchant, etc.)
- Colors must be natural, rich, period-appropriate: think heraldic tones, earth tones, jewel tones
- Each characteristic must be a vivid descriptive phrase (8-20 words), not a single word
- The character should clearly reflect the AI agent's actual domain and purpose
- If the concept suggests multiple roles, blend them into one cohesive medieval character`, concept)

	url := fmt.Sprintf("%s/models/%s:generateContent", geminiBase, flashModel)

	reqBody := map[string]interface{}{
		"contents": []map[string]interface{}{
			{"parts": []map[string]string{{"text": instruction}}},
		},
		"generationConfig": map[string]interface{}{
			"temperature": 0.7,
			// Gemini'nin dogrudan JSON donmesini saglar
			"response_mime_type": "application/json",
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("gemini profile request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gemini profile error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, fmt.Errorf("decode profile response: %w", err)
	}

	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("empty profile response from gemini")
	}

	rawJSON := apiResp.Candidates[0].Content.Parts[0].Text

	var profile AgentProfile
	if err := json.Unmarshal([]byte(rawJSON), &profile); err != nil {
		return nil, fmt.Errorf("parse profile JSON: %w", err)
	}

	return &profile, nil
}

// GenerateAvatarImage builds a medieval fantasy portrait prompt from an AgentProfile and calls
// Imagen to generate the avatar. The character is an upper-body portrait (belly upward) in
// three-quarter view with a solid magenta (#FF00FF) background for chroma key removal.
func (g *GeminiService) GenerateAvatarImage(profile *AgentProfile) (string, error) {
	return g.callImagen("Game character asset, " + BuildAvatarPrompt(profile))
}

// callImagen sends a text-to-image request to Imagen and returns a base64-encoded PNG.
func (g *GeminiService) callImagen(prompt string) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("gemini api key not configured")
	}
	url := fmt.Sprintf("%s/models/%s:predict", geminiBase, imagenModel)

	reqBody := map[string]interface{}{
		"instances": []map[string]interface{}{
			{"prompt": prompt},
		},
		"parameters": map[string]interface{}{
			"sampleCount":      1,
			"aspectRatio":      "1:1",
			"personGeneration": "ALLOW_ADULT",
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("imagen request: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("imagen error %d: %s", resp.StatusCode, string(respBody))
	}

	var imgResp struct {
		Predictions []struct {
			BytesBase64Encoded string `json:"bytesBase64Encoded"`
			MimeType           string `json:"mimeType"`
		} `json:"predictions"`
	}
	if err := json.Unmarshal(respBody, &imgResp); err != nil {
		return "", fmt.Errorf("parse imagen response: %w", err)
	}

	if len(imgResp.Predictions) == 0 || imgResp.Predictions[0].BytesBase64Encoded == "" {
		return "", fmt.Errorf("no image in imagen response (likely safety filter triggered). Raw response: %s", string(respBody))
	}

	return imgResp.Predictions[0].BytesBase64Encoded, nil
}

// GenerateImage calls Gemini Imagen 3 and returns a base64-encoded PNG string.
// Kept as a legacy/fallback method; prefer GenerateAvatarImage for new agents.
func (g *GeminiService) GenerateImage(imagePrompt, charType string) (string, error) {
	style := charTypeStyles[charType]
	if style == "" {
		style = "medieval fantasy character, rich painterly illustration"
	}

	fullPrompt := style + ". " + imagePrompt +
		" Style: detailed 2D medieval fantasy illustration, warm painterly tones, " +
		"storybook RPG art, centered character, contextual background, " +
		"no text, no watermark, square composition."

	return g.callImagen(fullPrompt)
}

// sanitizeProfile ensures all required fields in the profile have reasonable values.
func sanitizeProfile(p AgentProfile) AgentProfile {
	if p.PrimaryColor == "" {
		p.PrimaryColor = "Royal Purple"
	}
	if p.SecondaryColor == "" {
		p.SecondaryColor = "Burnished Gold"
	}
	if p.TabletGlowColor == "" {
		p.TabletGlowColor = "Amber"
	}
	if len(p.Characteristics) < 4 {
		defaults := []string{
			"a deep hood casting shadow over a weathered but wise face",
			"layered travelling robes with a leather belt and iron buckle",
			"faint arcane runes drifting in the air around the shoulders",
			"a gnarled oak staff topped with a softly glowing crystal",
		}
		for len(p.Characteristics) < 4 {
			p.Characteristics = append(p.Characteristics, defaults[len(p.Characteristics)])
		}
	}
	return p
}

// extractCharacteristics safely extracts the four characteristic fields from the LLM output.
// Order: [0]=headwear/face, [1]=outfit, [2]=unique visual feature, [3]=held item.
// It strips any leading numbering (e.g. "1. ", "10. ", "1) ", "- ") that the model may include.
func extractCharacteristics(chars []string) (headwear, outfit, uniqueFeature, heldItem string) {
	get := func(i int, fallback string) string {
		if i >= len(chars) {
			return fallback
		}
		s := strings.TrimSpace(chars[i])
		// Strip common LLM numbering prefixes: "1. ", "10. ", "1) ", "- ", "* "
		for len(s) > 0 {
			if s[0] >= '0' && s[0] <= '9' {
				// Skip digits
				j := 0
				for j < len(s) && s[j] >= '0' && s[j] <= '9' {
					j++
				}
				// Expect ". " or ") " after digits
				if j < len(s) && (s[j] == '.' || s[j] == ')') {
					rest := s[j+1:]
					s = strings.TrimSpace(rest)
					continue
				}
			}
			if strings.HasPrefix(s, "- ") || strings.HasPrefix(s, "* ") {
				s = strings.TrimSpace(s[2:])
				continue
			}
			break
		}
		if s == "" {
			return fallback
		}
		return s
	}
	headwear = get(0, "a deep hood casting shadow over a weathered but wise face")
	outfit = get(1, "layered travelling robes with a leather belt and iron buckle")
	uniqueFeature = get(2, "faint arcane runes drifting in the air around the shoulders")
	heldItem = get(3, "a gnarled oak staff topped with a softly glowing crystal")
	return
}

// Chat sends a user message to Gemini Flash using systemPrompt via the dedicated
// systemInstruction field (instead of combining into a single turn) for better adherence.
func (g *GeminiService) Chat(systemPrompt, userMessage string) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("gemini api key not configured")
	}

	url := fmt.Sprintf("%s/models/%s:generateContent", geminiBase, flashModel)

	reqBody := map[string]interface{}{
		"systemInstruction": map[string]interface{}{
			"parts": []map[string]string{{"text": systemPrompt}},
		},
		"contents": []map[string]interface{}{
			{
				"role":  "user",
				"parts": []map[string]string{{"text": userMessage}},
			},
		},
		"generationConfig": map[string]interface{}{
			"maxOutputTokens": 1024,
			"temperature":     0.8,
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-goog-api-key", g.apiKey)

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("gemini chat request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("gemini chat error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return "", fmt.Errorf("decode chat response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("empty chat response from gemini")
	}

	return strings.TrimSpace(apiResp.Candidates[0].Content.Parts[0].Text), nil
}

// sanitizeAnalysis ensures all returned fields are valid known values.
func sanitizeAnalysis(a PromptAnalysis) PromptAnalysis {
	validTypes := map[string]bool{
		"wizard": true, "strategist": true, "oracle": true, "guardian": true,
		"artisan": true, "bard": true, "scholar": true, "merchant": true,
	}
	validCategories := map[string]bool{
		"backend": true, "frontend": true, "data": true, "security": true,
		"creative": true, "business": true, "research": true, "general": true,
	}
	validRarities := map[string]bool{
		"common": true, "uncommon": true, "rare": true, "epic": true, "legendary": true,
	}

	a.CharacterType = strings.ToLower(strings.TrimSpace(a.CharacterType))
	if !validTypes[a.CharacterType] {
		a.CharacterType = "wizard"
	}

	a.Category = strings.ToLower(strings.TrimSpace(a.Category))
	if !validCategories[a.Category] {
		a.Category = "general"
	}

	a.Rarity = strings.ToLower(strings.TrimSpace(a.Rarity))
	if !validRarities[a.Rarity] {
		a.Rarity = "common"
	}

	if len(a.Tags) == 0 {
		a.Tags = []string{a.Category}
	}
	if len(a.Tags) > 5 {
		a.Tags = a.Tags[:5]
	}

	if a.Subclass == "" {
		a.Subclass = defaultSubclass[a.CharacterType]
	}

	return a
}
