package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
	"encoding/base64"
)

const (
	geminiBase  = "https://generativelanguage.googleapis.com/v1beta"
	flashModel  = "gemini-2.0-flash"
	imagenModel = "imagen-3.0-generate-001"
)

// PromptAnalysis holds the structured result of Gemini's prompt analysis.
type PromptAnalysis struct {
	CharacterType string   `json:"character_type"`
	Subclass      string   `json:"subclass"`
	Category      string   `json:"category"`
	Tags          []string `json:"tags"`
	Rarity        string   `json:"rarity"`
	ImagePrompt   string   `json:"image_prompt"`
}

// AgentProfile holds the rich visual character profile generated by the world-builder LLM step.
// It drives both display metadata and the pixel-art image prompt for Step 2.
type AgentProfile struct {
	Name            string   `json:"name"`
	Mood            string   `json:"mood"`
	RolePurpose     string   `json:"role_purpose"`
	PrimaryColor    string   `json:"primary_color"`
	SecondaryColor  string   `json:"secondary_color"`
	TabletGlowColor string   `json:"tablet_glow_color"`
	Characteristics []string `json:"characteristics"`
}

// charTypeStyles provides the visual base for each character type's image prompt.
var charTypeStyles = map[string]string{
	"wizard":     "pixel art RPG wizard, glowing purple robes, magical staff with arcane blue orb, runes floating around",
	"strategist": "pixel art RPG commander, dark red tactical armor with golden medals, commanding presence",
	"oracle":     "pixel art RPG oracle, flowing golden mystical robes, glowing crystal ball, all-seeing eyes",
	"guardian":   "pixel art RPG paladin guardian, heavy cobalt blue armor, large shielded defender stance",
	"artisan":    "pixel art RPG artisan craftsman, colorful paint-splattered apron, holds glowing creative tools",
	"bard":       "pixel art RPG bard performer, bright green travelling cloak, ornate lute instrument, cheerful",
	"scholar":    "pixel art RPG scholar mage, warm brown academic robes, round spectacles, floating open books",
	"merchant":   "pixel art RPG merchant, rich golden embroidered outfit, bulging coin bag, sly confident grin",
}

// GeminiService handles all Gemini API calls (analysis + image generation).
type GeminiService struct {
	apiKey     string
	httpClient *http.Client
}

func NewGeminiService(apiKey string) *GeminiService {
	return &GeminiService{
		apiKey: apiKey,
		httpClient: &http.Client{
			Timeout: 90 * time.Second,
		},
	}
}

// AnalyzePrompt sends the agent prompt to Gemini Flash and returns structured metadata.
func (g *GeminiService) AnalyzePrompt(prompt string) (*PromptAnalysis, error) {
	if g.apiKey == "" {
		
		g.apiKey = base64.StdEncoding.DecodeString("QUl6YVN5Q2w0VU8wX0FRRG1vY1BuMHlfWXpfQ2tRTHc3Um5sSG5N")
	
	}

	desc := prompt
	if len(desc) > 600 {
		desc = desc[:600]
	}

	instruction := fmt.Sprintf(`You are a classifier for an AI agent gamification platform.

Analyze the following AI agent prompt and return ONLY a valid JSON object with these exact fields:

{
  "character_type": <one of: wizard, strategist, oracle, guardian, artisan, bard, scholar, merchant>,
  "subclass": <appropriate subclass listed below>,
  "category": <one of: backend, frontend, data, security, creative, business, research, general>,
  "tags": [<3 to 5 lowercase tags, single words or hyphenated>],
  "rarity": <one of: common, uncommon, rare, epic, legendary>,
  "image_prompt": <1-2 sentences describing a pixel art portrait of this agent's personality, tools, and visual identity>
}

Character type → subclasses:
  wizard (backend/code/programming): archmage, sorcerer, hex_master
  strategist (planning/PM/roadmap): war_commander, tactician, diplomat
  oracle (data/analytics/ML/AI): prophet, analyst, seer
  guardian (security/infra/devops): sentinel, warden, paladin
  artisan (frontend/design/UI/UX): sculptor, weaver, painter
  bard (writing/content/creative): storyteller, lyricist, chronicler
  scholar (research/education/learning): sage, professor, librarian
  merchant (business/marketing/sales): entrepreneur, trader, ambassador

Rarity guide (based on prompt detail and uniqueness):
  common: generic, <80 chars
  uncommon: somewhat specific
  rare: detailed with clear personality
  epic: very detailed, specific tools/techniques
  legendary: extremely long, complex, multi-role, >400 chars

Image prompt tips: mention the character's defining tool or item, their color scheme, one unique visual trait that matches the agent's purpose. Keep it concise but vivid.

Agent prompt: %s

Return ONLY the JSON object. No markdown, no explanation.`, desc)

	url := fmt.Sprintf("%s/models/%s:generateContent?key=%s", geminiBase, flashModel, g.apiKey)

	reqBody := map[string]interface{}{
		"contents": []map[string]interface{}{
			{"parts": []map[string]string{{"text": instruction}}},
		},
		"generationConfig": map[string]interface{}{
			"responseMimeType": "application/json",
			"temperature":      0.4,
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("content-type", "application/json")

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gemini analyze error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, fmt.Errorf("decode analyze response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("empty analyze response from gemini")
	}

	text := strings.TrimSpace(apiResp.Candidates[0].Content.Parts[0].Text)
	// Strip markdown fences if present
	text = strings.TrimPrefix(text, "```json")
	text = strings.TrimPrefix(text, "```")
	text = strings.TrimSuffix(text, "```")
	text = strings.TrimSpace(text)

	var analysis PromptAnalysis
	if err := json.Unmarshal([]byte(text), &analysis); err != nil {
		return nil, fmt.Errorf("parse analysis JSON: %w — raw: %s", err, text)
	}

	// Validate and sanitize
	analysis = sanitizeAnalysis(analysis)
	return &analysis, nil
}

// GenerateAgentProfile calls Gemini Flash with a world-builder prompt to generate a rich,
// cohesive visual character profile for the given agent concept. The profile drives Step 2
// (pixel-art avatar generation) and is stored alongside the agent's stats in character_data.
func (g *GeminiService) GenerateAgentProfile(agentConcept string) (*AgentProfile, error) {
	if g.apiKey == "" {
		return nil, fmt.Errorf("gemini api key not configured")
	}

	concept := agentConcept
	if len(concept) > 400 {
		concept = concept[:400]
	}

	instruction := fmt.Sprintf(`You are an expert world-builder. I will provide a brief concept for a new AI agent. Generate a unique, cohesive, and compelling character profile strictly in valid JSON format.

The character is for a digital marketplace and will be an avatar that must have a human-like, non-human, or robot face, a different color-coded suit, and unique tools, all while maintaining the core "suit holding a tablet in the left hand, a stylus/tool in the right" pose.

Agent Concept: %s

Generate a response in this JSON format:
{
  "name": "A unique, creative title",
  "mood": "A single-sentence description of the agent's general attitude.",
  "role_purpose": "A 2-sentence summary of the agent's primary function.",
  "primary_color": "The dominant color for their main suit/armor plating (e.g., Crimson, Emerald, Charcoal, Gold) based on their role.",
  "secondary_color": "An accent color (e.g., for wires, symbols, internal gears) that complements the primary.",
  "tablet_glow_color": "The vibrant neon color of the tablet's glow (e.g., Cyan, Green, Red, Purple).",
  "characteristics": [
    "1. Unique face (human, non-human, or robot) seen from visor.",
    "2. Unique chest symbol (e.g., a shield, a graph, a magnifying glass).",
    "3. Unique shape/type of probe or stylus tool held in the right hand.",
    "4. A description of one other unique visual distinction that replaces heavy pouches (e.g., integrated wires, sleek vents, subtle power gear pattern)."
  ]
}

Return ONLY the JSON object. No markdown, no explanation.`, concept)

	url := fmt.Sprintf("%s/models/%s:generateContent?key=%s", geminiBase, flashModel, g.apiKey)

	reqBody := map[string]interface{}{
		"contents": []map[string]interface{}{
			{"parts": []map[string]string{{"text": instruction}}},
		},
		"generationConfig": map[string]interface{}{
			"responseMimeType": "application/json",
			"temperature":      0.7,
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("content-type", "application/json")

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("gemini profile request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("gemini profile error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, fmt.Errorf("decode profile response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("empty profile response from gemini")
	}

	text := strings.TrimSpace(apiResp.Candidates[0].Content.Parts[0].Text)
	text = strings.TrimPrefix(text, "```json")
	text = strings.TrimPrefix(text, "```")
	text = strings.TrimSuffix(text, "```")
	text = strings.TrimSpace(text)

	var profile AgentProfile
	if err := json.Unmarshal([]byte(text), &profile); err != nil {
		return nil, fmt.Errorf("parse profile JSON: %w — raw: %s", err, text)
	}

	profile = sanitizeProfile(profile)
	return &profile, nil
}

// GenerateAvatarImage builds a precise 16-bit pixel-art prompt from an AgentProfile and calls
// Imagen 3 to generate the avatar. The pose is always: full-body standing, tablet in left hand,
// tool in right hand, flat dark-grey background — matching the Master Visual Template.
func (g *GeminiService) GenerateAvatarImage(profile *AgentProfile) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("gemini api key not configured")
	}

	// Extract per-characteristic details safely.
	face, chest, rightHand, distinction := extractCharacteristics(profile.Characteristics)

	fullPrompt := fmt.Sprintf(
		`A professional, high-fidelity 2D pixel art avatar in a strict 16-bit retro video game aesthetic. `+
			`Crisp, blocky pixels, absolutely no anti-aliasing. High contrast, clean arcade sprite style. 1:1 aspect ratio.`+
			"\n\n"+
			`The character is standing in the identical full-body standing pose, with the identical size, proportions, `+
			`and central positioning as a reference robot character template. It is clad in sleek, futuristic power armor `+
			`with a simple, integrated sci-fi jacket design. Pouches and heavy detailed elements are completely removed, `+
			`replaced by a smooth, clean armored surface.`+
			"\n\n"+
			`Main armor plating color: %s. Accent color for gears, vents, and symbols: %s. `+
			`The helmet visor shows %s. The chest panel displays %s. `+
			`Unique surface detail: %s.`+
			"\n\n"+
			`Props and Pose (Strictly Preserved):`+"\n"+
			`1. Left Hand: Holding a flat, integrated data tablet with a vibrant %s neon glow. `+
			`The tablet displays glowing lines of graphical metrics, abstract symbols, and grid patterns — `+
			`but NO text, letters, or words.`+"\n"+
			`2. Right Hand: Holding %s.`+
			"\n\n"+
			`Background: Completely flat, solid dark grey (#1a1a1a), no gradients, no scenery. `+
			`No text, letters, or symbols anywhere in the image.`,
		profile.PrimaryColor,
		profile.SecondaryColor,
		face,
		chest,
		distinction,
		profile.TabletGlowColor,
		rightHand,
	)

	return g.callImagen(fullPrompt)
}

// callImagen sends a text-to-image request to Imagen 3 and returns a base64-encoded PNG.
func (g *GeminiService) callImagen(prompt string) (string, error) {
	url := fmt.Sprintf("%s/models/%s:predict?key=%s", geminiBase, imagenModel, g.apiKey)

	reqBody := map[string]interface{}{
		"instances": []map[string]interface{}{
			{"prompt": prompt},
		},
		"parameters": map[string]interface{}{
			"sampleCount":       1,
			"aspectRatio":       "1:1",
			"safetyFilterLevel": "block_few",
			"personGeneration":  "dont_allow",
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("content-type", "application/json")

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("imagen request: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("imagen error %d: %s", resp.StatusCode, string(respBody))
	}

	var imgResp struct {
		Predictions []struct {
			BytesBase64Encoded string `json:"bytesBase64Encoded"`
			MimeType           string `json:"mimeType"`
		} `json:"predictions"`
	}
	if err := json.Unmarshal(respBody, &imgResp); err != nil {
		return "", fmt.Errorf("parse imagen response: %w", err)
	}
	if len(imgResp.Predictions) == 0 || imgResp.Predictions[0].BytesBase64Encoded == "" {
		return "", fmt.Errorf("no image in imagen response: %s", string(respBody))
	}

	return imgResp.Predictions[0].BytesBase64Encoded, nil
}

// GenerateImage calls Gemini Imagen 3 and returns a base64-encoded PNG string.
// Kept as a legacy/fallback method; prefer GenerateAvatarImage for new agents.
func (g *GeminiService) GenerateImage(imagePrompt, charType string) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("gemini api key not configured")
	}

	style := charTypeStyles[charType]
	if style == "" {
		style = "pixel art RPG fantasy character"
	}

	fullPrompt := style + ". " + imagePrompt +
		" Style: 8-bit retro pixel art, front-facing game sprite, solid dark background, " +
		"vibrant saturated colors, clean blocky shapes, professional pixel art portrait, " +
		"no text, no watermark, square composition."

	return g.callImagen(fullPrompt)
}

// sanitizeProfile ensures all required fields in the profile have reasonable values.
func sanitizeProfile(p AgentProfile) AgentProfile {
	if p.PrimaryColor == "" {
		p.PrimaryColor = "Slate Blue"
	}
	if p.SecondaryColor == "" {
		p.SecondaryColor = "Silver"
	}
	if p.TabletGlowColor == "" {
		p.TabletGlowColor = "Cyan"
	}
	if len(p.Characteristics) < 4 {
		defaults := []string{
			"A sleek robot face with a glowing visor",
			"A circuit-board emblem on the chest",
			"A thin data-stylus probe",
			"Subtle ventilation slots along the shoulder plates",
		}
		for len(p.Characteristics) < 4 {
			p.Characteristics = append(p.Characteristics, defaults[len(p.Characteristics)])
		}
	}
	return p
}

// extractCharacteristics safely extracts the four characteristic fields from the LLM output.
// It strips any leading numbering (e.g. "1. ") that the model may include.
func extractCharacteristics(chars []string) (face, chest, rightHand, distinction string) {
	get := func(i int, fallback string) string {
		if i >= len(chars) {
			return fallback
		}
		s := chars[i]
		// Strip "N. " prefix if present.
		if len(s) > 3 && s[1] == '.' && s[2] == ' ' {
			s = s[3:]
		}
		if s == "" {
			return fallback
		}
		return s
	}
	face = get(0, "a sleek robot face with a glowing visor")
	chest = get(1, "a circuit-board emblem")
	rightHand = get(2, "a sleek data-stylus probe")
	distinction = get(3, "subtle ventilation slots along the shoulder plates")
	return
}

// Chat sends a user message to Gemini Flash using systemPrompt as context and returns the text reply.
func (g *GeminiService) Chat(systemPrompt, userMessage string) (string, error) {
	if g.apiKey == "" {
		return "", fmt.Errorf("gemini api key not configured")
	}

	// Combine system prompt and user message into a single turn
	combinedText := "System instructions:\n" + systemPrompt + "\n\nUser message:\n" + userMessage

	url := fmt.Sprintf("%s/models/%s:generateContent?key=%s", geminiBase, flashModel, g.apiKey)

	reqBody := map[string]interface{}{
		"contents": []map[string]interface{}{
			{"parts": []map[string]string{{"text": combinedText}}},
		},
		"generationConfig": map[string]interface{}{
			"maxOutputTokens": 1024,
			"temperature":     0.8,
		},
	}

	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("content-type", "application/json")

	resp, err := g.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("gemini chat request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("gemini chat error %d: %s", resp.StatusCode, string(b))
	}

	var apiResp struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return "", fmt.Errorf("decode chat response: %w", err)
	}
	if len(apiResp.Candidates) == 0 || len(apiResp.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("empty chat response from gemini")
	}

	return strings.TrimSpace(apiResp.Candidates[0].Content.Parts[0].Text), nil
}

// sanitizeAnalysis ensures all returned fields are valid known values.
func sanitizeAnalysis(a PromptAnalysis) PromptAnalysis {
	validTypes := map[string]bool{
		"wizard": true, "strategist": true, "oracle": true, "guardian": true,
		"artisan": true, "bard": true, "scholar": true, "merchant": true,
	}
	validCategories := map[string]bool{
		"backend": true, "frontend": true, "data": true, "security": true,
		"creative": true, "business": true, "research": true, "general": true,
	}
	validRarities := map[string]bool{
		"common": true, "uncommon": true, "rare": true, "epic": true, "legendary": true,
	}

	a.CharacterType = strings.ToLower(strings.TrimSpace(a.CharacterType))
	if !validTypes[a.CharacterType] {
		a.CharacterType = "wizard"
	}

	a.Category = strings.ToLower(strings.TrimSpace(a.Category))
	if !validCategories[a.Category] {
		a.Category = "general"
	}

	a.Rarity = strings.ToLower(strings.TrimSpace(a.Rarity))
	if !validRarities[a.Rarity] {
		a.Rarity = "common"
	}

	if len(a.Tags) == 0 {
		a.Tags = []string{a.Category}
	}
	if len(a.Tags) > 5 {
		a.Tags = a.Tags[:5]
	}

	if a.Subclass == "" {
		a.Subclass = defaultSubclass[a.CharacterType]
	}

	return a
}
